import { Job } from "@/types/jobs";

export  const JobsData : Job[] = [
  {
    id: 1,
    image: "../../Assets/logo.png",
    title: "Web Developer",
    time: "Now",
    location: "Canada",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Netflix",
  },
  {
    id: 2,
    image: "../../Assets/logo1.png",
    title: "UI Designer",
    time: "14Hrs",
    location: "Manchester",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Google",
  },
  {
    id: 3,
    image: "../../Assets/logo2.png",
    title: "Software Eng.",
    time: "Now",
    location: "Austria",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 4,
    image: "../../Assets/logo3.png",
    title: "Frontend Eng.",
    time: "2Mnths.",
    location: "Turkey",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 5,
    image: "../../Assets/logo4.png",
    title: "Backend Dev.",
    time: "12Hrs",
    location: "South Korea",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 6,
    image: "../../Assets/logo7.png",
    title: "Web Developer",
    time: "Now",
    location: "Canada",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Netflix",
  },
  {
    id: 7,
    image: "../../Assets/logo4.png",
    title: "UI Designer",
    time: "14Hrs",
    location: "Manchester",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Google",
  },
  {
    id: 8,
    image: "../../Assets/logo4.png",
    title: "Software Eng.",
    time: "Now",
    location: "Austria",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 9,
    image: "../../Assets/logo4.png",
    title: "Frontend Eng.",
    time: "2Mnths.",
    location: "Turkey",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 10,
    image: "../../Assets/logo4.png",
    title: "Backend Dev.",
    time: "12Hrs",
    location: "South Korea",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Instagram",
  },
  {
    id: 11,
    image: "../../Assets/logo4.png",
    title: "Web Developer",
    time: "Now",
    location: "Canada",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Netflix",
  },
  {
    id: 12,
    image: "../../Assets/logo4.png",
    title: "UI Designer",
    time: "14Hrs",
    location: "Manchester",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    company: "Google",
  },
];